name: Wazuh Cloud Logging

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  log_activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Log activity to Wazuh Cloud
        env:
          WAZUH_API_KEY: ${{ secrets.WAZUH_API_KEY }}
        run: |
          python -c "
          import requests
          import json
          
          api_key = '${{ secrets.WAZUH_API_KEY }}'
          url = 'https://YOUR_WAZUH_CLOUD_INSTANCE/api/v4/agents'

          headers = {
              'Authorization': f'Bearer {api_key}',
              'Content-Type': 'application/json'
          }

          response = requests.get(url, headers=headers)

          if response.status_code == 200:
              print('Successfully fetched data from Wazuh Cloud')
              print(json.dumps(response.json(), indent=4))
          else:
              print(f'Failed to fetch data: {response.status_code} - {response.text}')
          "

